### ISSUE TITLE
Readme.md 语法错误

### ISSUE THREAD

**Issue by yangezheng** [vczh/herodb#2]
# 语法错误！

![image](https://user-images.githubusercontent.com/18118996/29773303-0b0e029a-8bfd-11e7-99b2-99284477e1fe.png)

### will 后面接**动词原型**
![image](https://user-images.githubusercontent.com/18118996/29773316-1889ca94-8bfd-11e7-937b-490ba46de64c.png)

**Comment by vczh** [comment]
Fixed
